apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      serviceAccountName: {{ .Values.app.serviceAccount }}

      initContainers:
        - name: init-data
          image: busybox
          command: ["sh", "-c", "mkdir -p /data && echo 'folder ready'"]
          volumeMounts:
            - mountPath: /data
              name: data-volume

      containers:
        - name: main-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: APP_MODE
              valueFrom:
                configMapKeyRef:
                  name: main-configmap
                  key: APP_MODE
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: main-configmap
                  key: MESSAGE
            - name: DATA_PATH
              valueFrom:
                configMapKeyRef:
                  name: main-configmap
                  key: DATA_PATH
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: main-secret
                  key: API_TOKEN
          volumeMounts:
            - mountPath: /data
              name: data-volume
            - mountPath: /logs
              name: logs-volume

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.probes.readinessDelay }}
            periodSeconds: {{ .Values.probes.readinessPeriod }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.probes.livenessDelay }}
            periodSeconds: {{ .Values.probes.livenessPeriod }}

        - name: sidecar-log
          image: busybox:1.36
          command:
            ["sh", "-c", "tail -F /logs/app.log 2>/dev/null || sleep infinity"]
          volumeMounts:
            - mountPath: /logs
              name: logs-volume

      volumes:
        - name: logs-volume
          emptyDir: {}
        - name: data-volume
          persistentVolumeClaim:
            claimName: main-pvc
