apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  name: audit-notes-networkpolicy
  namespace: {{ .Values.namespace }}

spec:
  podSelector:
    matchLabels:
      app: {{ .Values.app.name }}

  policyTypes:
    - Ingress

  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.containerPort }}