name: Deploy Application

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-central-1
  K8S_NAMESPACE: audit

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: arn:aws:iam::483955238384:role/github-actions-role
            aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init #Get output from that S3 Bucket, he has all info from our infra.yml
        run: terraform -chdir=terraform/environments/dev init
    
      - name: Get Terraform Outputs
        id: terraform
        run: |
            cd terraform/environments/dev
            echo "cluster_name=$(terraform output -raw cluster_name)" >> $GITHUB_OUTPUT

      - name: Verify kubectl
        run: kubectl version --client

      - name: Configure kubectl #Say to our kubectl to use that cluster
        run: |
            aws eks update-kubeconfig \
            --name ${{ steps.terraform.outputs.cluster_name }} \
            --region ${{ env.AWS_REGION }}

      - name: Verify Cluster Connection
        run: |
            kubectl get nodes


      - name: Verify Helm
        run: helm version

      - name: Deploy Application
        run: |
            helm upgrade --install audit-notes-service \
            ./helm \
            --namespace ${{ env.K8S_NAMESPACE }} \
            --create-namespace \
            --wait \
            --timeout 10m

      - name: Wait for Deployment
        run: |
            kubectl rollout status deployment/main-deployment \
            -n ${{ env.K8S_NAMESPACE }} \
            --timeout=10m

      - name: Verify Deployment
        run: |
            kubectl get pods -n ${{ env.K8S_NAMESPACE }}
            kubectl get svc -n ${{ env.K8S_NAMESPACE }}
            kubectl get ingress -n ${{ env.K8S_NAMESPACE }}
            kubectl get pvc -n ${{ env.K8S_NAMESPACE }}